### ISSUE TITLE
属性介绍

### ISSUE THREAD

**Issue by mengqian277** [yw0525/mina-component#45]
博主你好！这些组件有没有属性介绍呢？引入了不知道有哪些属性和API嘞

**Comment by lavender1026** [comment]
https://developers.weixin.qq.com/community/develop/article/doc/0002a61cb3ca60815e9b533e15b813

**Comment by yw0525** [comment]
不好意思，刚刚看到。代码中存在 examples 文件夹，可以先看下基本用法，后面我更新下详细文档。

**Comment by yw0525** [comment]
> 博主你好！这些组件有没有属性介绍呢？引入了不知道有哪些属性和API嘞

不好意思，刚刚看到。目前代码中存在 examples 文件夹，可以先看下基本用法，后面我更新下详细文档。

**Comment by yzqzy** [comment]
packages 组件目录下，有 demo 目录，里面就是使用案例。
源代码已经在根目录下，examples 目录就是微信小程序，里面引用 packages 下的组件。
